### ISSUE TITLE
Issue with app on Windows 10 22H2 19045.3448

### ISSUE THREAD

**Issue by awkitsune** [EshSub/Productiv#3]
![image](https://github.com/EshSub/Productiv/assets/45891293/d25fbbff-b8db-4588-8192-f7b46b9098d4)
Here is my winver screenshot.

The issue is when app is opened and any window state changes app shows winforms error dialog and nothing happens with any maximised window. If it's needed I can show some logs from the subject

**Comment by EshSub** [comment]
I havent tested in windows 10. I will try to make it work for windows 10 as well.

**Comment by awkitsune** [comment]
Oh, so it's not supposed to work on windows 10?

**Comment by EshSub** [comment]
In the app we use undocumented windows apis. So cant for sure tell which versions it works on or not without actually trying on that specific windows version. So Not sure if it works in windows 10,cuz I haven't tested on a windows 10 machine. Will check and put a fix.

**Comment by Hau-Hau** [comment]
I have exactly same build and same problem.
I don't had time to take a deep look into code - @EshSub could you confirm if [VirtualDesktop11-23H2.cs](https://github.com/EshSub/Productiv/blob/master/VirtualDesktopAdapters/VirtualDesktop11-23H2.cs ) is only class through which Productiv is accessing private api?

**Comment by EshSub** [comment]
@Hau-Hau 
Yes. Its what I use currently.
Its taken from the repo [virtual desktop](https://github.com/MScholtes/VirtualDesktop). It has seperate programs written from windows versions. 
We should implement platform specific functions to make this work across multiple windows versions by using the versions from that repo.

**Comment by EshSub** [comment]
Added a windows 10 version. Couldnt test it though. Can you guys check and let me know if it works. Thank you in advance
@Hau-Hau @awkitsune

**Comment by awkitsune** [comment]
So, it's still doesn't work. 
when I maximize the window it shows this window 
![image](https://github.com/EshSub/Productiv/assets/45891293/90d65c56-484e-4946-96e4-0de712570c73)
with such error message
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for 'VirtualDesktop11.DesktopManager' threw an exception.
 ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop11.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop11.DesktopManager..cctor() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktop11.cs:line 237
   --- End of inner exception stack trace ---
   at VirtualDesktop11.Desktop.Create() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktop11.cs:line 459
   at Productiv.VirtualDesktopAdapters.CreateAndMoveToNewDesktop(IntPtr handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktopAdapters.cs:line 27
   at Productiv.EventHandlers.OnMaximize(IntPtr handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\EventHandlers.cs:line 57
   at GlobalHooksTest.Form1._GlobalHooks_CbtMinMax(IntPtr Handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 943
   at GlobalHooksTest.GlobalHooks.CBTHook.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 267
   at GlobalHooksTest.GlobalHooks.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 99
   at GlobalHooksTest.Form1.WndProc(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 259
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.CoreLib.dll
----------------------------------------
Productiv
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EshSub/Productiv/Productiv.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.Specialized.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/Microsoft.Win32.Registry.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Drawing.Common.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Threading.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Console.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Net.WebClient.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.Immutable.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------

************** JIT Debugging **************



```

**Comment by EshSub** [comment]
Okay. thanks for the feedback. Will try to put a fix asap.

**Comment by EshSub** [comment]
I've added a new build. Can you check whether it works and let me know. Thanks in advance.
@awkitsune

**Comment by awkitsune** [comment]
Now it kinda works, windows are moved to the new workspace but something is still wrong. Error appears and here is the message: 
![image](https://github.com/EshSub/Productiv/assets/45891293/e30a6b2f-1412-42ba-ba46-24617effd4bc)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
   at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at VirtualDesktop.Desktop.SetName(String Name) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktop.cs:line 527
   at Productiv.VirtualDesktopAdapters.CreateAndMoveToNewDesktop(IntPtr handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktopAdapters.cs:line 33
   at Productiv.EventHandlers.OnMaximize(IntPtr handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\EventHandlers.cs:line 57
   at GlobalHooksTest.Form1._GlobalHooks_CbtMinMax(IntPtr Handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 943
   at GlobalHooksTest.GlobalHooks.CBTHook.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 267
   at GlobalHooksTest.GlobalHooks.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 99
   at GlobalHooksTest.Form1.WndProc(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 259
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.CoreLib.dll
----------------------------------------
Productiv
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EshSub/Productiv/Productiv.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.Specialized.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/Microsoft.Win32.Registry.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Drawing.Common.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Threading.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Console.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Net.WebClient.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.Immutable.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.Concurrent.dll
----------------------------------------

************** JIT Debugging **************



```

**Comment by EshSub** [comment]
Can you send a screenshot of the debug tab of the productiv window as well. @awkitsune

**Comment by queenbiscuit311** [comment]
I'm having this same issue on windows 10. The application appears to work just fine. Maximizing goes to a new desktop successfully, and minimizing goes back and removes the old desktop. But every time it brings up one of those .NET error windows.

![image](https://github.com/EshSub/Productiv/assets/88851292/a0ac8c71-0d87-49ad-bfd2-22ebcc981a74)

Trying to enable the debug options seems to make the app not work anymore, as it no longer does anything until its restarted. The most I can get out of it is this:

![image](https://github.com/EshSub/Productiv/assets/88851292/a1ea2b99-a590-462f-a3a9-d6f33ec17abf)


It also leaves this in the corner 
![image](https://github.com/EshSub/Productiv/assets/88851292/57e435d1-cbce-42a5-8210-3a86e419da48)

**Comment by EshSub** [comment]
Thank you for your feedback. Sorry I have been busy last couple of weeks. Will check and put a fix asap.
