### ISSUE TITLE
Not working with Windows11

### ISSUE THREAD

**Issue by flochaz** [EshSub/Productiv#6]
```
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.
 ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktop.cs:line 262
   --- End of inner exception stack trace ---
   at VirtualDesktop.Desktop.get_Current() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktop.cs:line 385
   at Productiv.VirtualDesktopAdapters.RemoveCurrent() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktopAdapters.cs:line 38
   at Productiv.EventHandlers.OnMinimze() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\EventHandlers.cs:line 63
   at GlobalHooksTest.Form1._GlobalHooks_CbtMinMax(IntPtr Handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 951
   at GlobalHooksTest.GlobalHooks.CBTHook.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 267
   at GlobalHooksTest.GlobalHooks.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 99
   at GlobalHooksTest.Form1.WndProc(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 259
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Assemblys chargés **************
System.Private.CoreLib
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Private.CoreLib.dll
----------------------------------------
Productiv
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Program%20Files%20(x86)/EshSub/Productiv/Productiv.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1823.27201
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.dll
----------------------------------------
System.Windows.Forms.Primitives
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1823.27201
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.Specialized.dll
----------------------------------------
System.Collections
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.dll
----------------------------------------
Microsoft.Win32.Registry
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/Microsoft.Win32.Registry.dll
----------------------------------------
System.Drawing.Common
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1823.26907
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Drawing.Common.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1823.26907
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Diagnostics.TraceSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Threading
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Threading.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.1823.27201
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1823.26907
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Memory.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1823.27201
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ObjectModel.dll
----------------------------------------
System.Linq
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1823.26907
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Console
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Console.dll
----------------------------------------
System.Text.Encoding.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Private.Uri
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Private.Uri.dll
----------------------------------------
System.Xml.ReaderWriter
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.WebClient.dll
----------------------------------------
System.Collections.NonGeneric
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Loader
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1823.27201
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/fr/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.Immutable.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.2023.32017
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------

************** Débogage JIT **************
```

**Comment by EshSub** [comment]
Thank you for reaching out, 
Did you run the app by installing a release version? If so, make sure you install the windows 11 release versions.
If you're running this from code base, as debug mode, change the imports in VirtualDesktopAdapters.cs and EventHandler.cs (Change the using VirtualDesktop1123H2 or VirtualDesktop11 depending on your version)
Please note that error handling is not implemented yet, so even if the app works error dialogs will be shown sometimes.

**Comment by flochaz** [comment]
Hi,

Thank you for your reply.
I can't find the win11 release, it may have not been published.

**Comment by EshSub** [comment]
Hi,
Here is the link to release for win 11,
[v1.0.1-alpha](https://github.com/EshSub/Productiv/releases/tag/v1.0.1-alpha)
Can you check it and confirm if it works. 
(Please delete the previous installed file and install the new version.)
Thank you.

**Comment by junoh-moon** [comment]
I tried v1.0.1-alpha on Windows11 22h2 and it seems to be working, I'll have to use it in long-term though :)

**Comment by EshSub** [comment]
Great. Since it works I will close the issue now. Thank you.
