### ISSUE TITLE
Error during lunching

### ISSUE THREAD

**Issue by Varrial** [EshSub/Productiv#7]
Hi there, I love idea of your app, especially i got mac for work and just build myslefw windows PC for gaming.
Anyway, I got win11, first I tried version 1.0.2win10 it didn't work... Next I have read Issues section and instaled v1.0.1-alpha.

I tried diffrent .NET versions because I didn't know witch one is needed. Finaly it lunches but I got this error when anything appering on screen. 
![image](https://github.com/EshSub/Productiv/assets/73936910/de0658bc-11b7-480f-b84c-06593a12bda6)

this error appers on both versions (I didn't have installed them on same time)

I got whis .net versions installed to lunch
![image](https://github.com/EshSub/Productiv/assets/73936910/a1c5d8cd-48eb-472a-8476-3c7163a90ac1)

This is full error information:

Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.
 ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VirtualDesktop.Desktop.get_Current()
   at Productiv.VirtualDesktopAdapters.IsCurrentDesktopUnamed() in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\VirtualDesktopAdapters.cs:line 51
   at Productiv.EventHandlers.OnCreateMinimized(IntPtr Handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\EventHandlers.cs:line 90
   at GlobalHooksTest.Form1._GlobalHooks_ShellWindowCreated(IntPtr Handle) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 921
   at GlobalHooksTest.GlobalHooks.ShellHook.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 376
   at GlobalHooksTest.GlobalHooks.ProcessWindowMessage(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\GlobalHooks.cs:line 100
   at GlobalHooksTest.Form1.WndProc(Message& m) in D:\PROJECTS\Global-CbtHook2\Global-CbtHook\GlobalHooksTestCore\Form1.cs:line 254
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Zestawy załadowane **************
System.Private.CoreLib
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Private.CoreLib.dll
----------------------------------------
Productiv
    Wersja zestawu: 0.0.0.0
    Wersja Win32: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EshSub/Productiv/Productiv.dll
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 6.0.2.0
    Wersja Win32: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.dll
----------------------------------------
System.Windows.Forms.Primitives
    Wersja zestawu: 6.0.2.0
    Wersja Win32: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Collections.Specialized.dll
----------------------------------------
System.Collections
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Collections.dll
----------------------------------------
Microsoft.Win32.Registry
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/Microsoft.Win32.Registry.dll
----------------------------------------
System.Drawing.Common
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Drawing.Common.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Diagnostics.TraceSource
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Threading
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Threading.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Memory.dll
----------------------------------------
System.Drawing
    Wersja zestawu: 6.0.2.0
    Wersja Win32: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.ObjectModel.dll
----------------------------------------
System.Linq
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Console
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Console.dll
----------------------------------------
System.Text.Encoding.Extensions
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Private.Uri
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Private.Uri.dll
----------------------------------------
System.Xml.ReaderWriter
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Net.WebClient.dll
----------------------------------------
System.Collections.NonGeneric
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Collections.NonGeneric.dll
----------------------------------------
VirtualDesktop
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EshSub/Productiv/VirtualDesktop.dll
----------------------------------------
System.Runtime.Loader
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Wersja zestawu: 6.0.2.0
    Wersja Win32: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.27/pl/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.27/System.Collections.Immutable.dll
----------------------------------------

************** Debugowanie w trybie JIT **************

**Comment by EshSub** [comment]
Sorry for the late response. Good news. I'll be starting working on this again. Expect an update soon.

**Comment by Varrial** [comment]
I'm glad to hear that

BTW 
You did great work ^^
